### PR TITLE
fix: get power supplies of type battery

### LINKED ISSUE #455: Questions about BAT0 or BAT1 in battery.sh
it doesn't exist on my lattop (LG, Ubuntu 24.04 and Ubuntu 20.04). My laptop only has CMB0. I replaced BAT0 in .sh with CMB0 to make it work properly.

### PR DESCRIPTION
**Pull request by xx4h**
* cleanup unused variables
* remove no longer needed directory test

fix #455

### CODE REVIEW

File: segments/battery.sh [hunk 1]
```diff
@@ -158,28 +146,26 @@ __linux_get_bat() {
...
+		if [ -r "$full" ] && [ -r "$now" ]; then
+			local bf
+			local bn
+			bf=$(cat "$full")
+			bn=$(cat "$now")
+			total_full=$((total_full + bf))
+			total_now=$((total_now + bn))
 		fi
-	done
+	done <<<"$(grep -l "Battery" /sys/class/power_supply/*/type | sed -e 's,/type$,,')"
```
Comment (erikw) [inline segments/battery.sh:168]: This looks like a better solution!

File: segments/battery.sh [hunk 2]
```diff
@@ -158,28 +146,26 @@ __linux_get_bat() {
...
-				bn=$(cat "$now")
-				total_full=$((total_full + bf))
-				total_now=$((total_now + bn))
-			fi
+		if [ -r "$full" ] && [ -r "$now" ]; then
+			local bf
+			local bn
+			bf=$(cat "$full")
+			bn=$(cat "$now")
+			total_full=$((total_full + bf))
```
Comment (erikw) [inline segments/battery.sh:165]: Good, summing up total battery is preserved.

**Review by erikw — APPROVED** [review]
I can't test the updated code myself at this moment, but the code changes looks good as far as I can see.

**Comment by xx4h** [comment]
> I can't test the updated code myself at this moment, but the code changes looks good as far as I can see.

I should have mentioned, that i tested it.
Only thing i can think of right now that could mess things up would be batteries with wrong type, or non-batteries with type "Battery".
