### PR TITLE
Fix vcs segments

### LINKED ISSUE #371: VCS segments not working for non-git repositories nested/down the path
The current state of the vcs segments always only checks until the first match is found (which is git in all the vcs segments). This leads to showing only data for the nearest git repository up the path.

**An example**

`PWD` is `/home/exampleuser/projects/hg-test`

| Normal folder | Git repo             | Normal folder | hg/mercurial repo |
|--------------------|----------------------|--------------------|-------------------------|
| /home             |  /exampleuser   |  /projects        | /hg-test                 |

tmux-powerline will now show (e.g. for `vcs_branch`, `vcs_compare`, `vcs_others` and the others) the data for the git repository but not for the hg one.

### PR DESCRIPTION
**Pull request by xx4h**
* add lib/vcs_helper.sh containing logic to return the closest vcs repository and its type (git, hg, svn)
* adapt all vcs_* segments to use logic from new lib
* add config vars to most of the vcs segments

fixes #371

### CODE REVIEW

File: segments/vcs_revision.sh [hunk 1]
```diff
@@ -3,41 +3,43 @@
 
 # Source lib to get the function get_tmux_pwd
 source "${TMUX_POWERLINE_DIR_LIB}/tmux_adapter.sh"
+source "${TMUX_POWERLINE_DIR_LIB}/vcs_helper.sh"
 
 run_segment() {
+	{ read vcs_type; read root_path; } < <(get_vcs_type_and_root_path)
```
Comment (erikw) [inline segments/vcs_revision.sh:9]: Cool, this construct is new to me

**Review by erikw — APPROVED** [review]
Good idea to refactor to lib

**Comment by erikw** [comment]
Thank you, looks good!
